# -*- coding: utf-8 -*-
"""3D 학생 역량 분석.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gy9nlIHD9VR0BZTl1ymO71LacO9hRWqV
"""

import pandas as pd
import numpy as np

# 데이터 불러오기
df = pd.read_csv('/content/2026 3D패션 학생 역량 분석(응답) - 설문지 응답 시트1.csv')

# 역량별 문항 묶기 (평균값 계산)
df['creativity'] = df[['1-1. 나는 새로운 아이디어를 떠올리는 것을 즐긴다.', '1-2. 문제 해결시 기존의 방식 외에도 창의적인 방법을 탐색한다.', '1-3. 나는 기존의 틀에서 벗어나 자유롭게 상상하는 편이다.', '1-4. 다양한 정보를 융합하여 새로운 아이디어를 만들어 낼 수 있다.']].mean(axis=1)
df['digital_skill'] = df[['4-1. 나는 디자인 소프트웨어(포토샵, 3D CLO 등)를 능숙하게 다룰 수 있다.', '4-2. 디지털 콘텐츠 제작 역량', '4-3. 다양한 디지털 플랫폼을 효과적으로 공유하거나 발표할 수 있다.', '4-4. 디지털 기술을 디자인 아이디어 실현을 위해 창의적으로 응용할 수 있다.']].mean(axis=1)
df['ai_usage'] = df[['15-1. 나는 생성형 AI를 이용해서 새로운 생각이나 아이디어를 만들어낼 수 있다.', '15-2. 나는   생성형 AI 의 도움으로 독창적인 글이나 이야기를 쓸 수 있다.', '15-3. 나는 생성형 AI를 사용해 복잡한 문제를 해결하는 새로운 방법을 찾아낼 수 있다.']].mean(axis=1)

# 로지스틱 회귀를 위한 이진 타겟 생성 (예: 상위 50%를 1로 설정)
df['is_high_ai'] = (df['ai_usage'] >= df['ai_usage'].median()).astype(int)

"""### 변수 간 상관관계 시각화

'creativity', 'digital_skill', 'ai_usage' 세 가지 주요 역량 변수 간의 상관관계를 히트맵으로 시각화하여 이들 사이의 상호 관련성을 분석합니다.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 상관관계 분석을 위한 변수 선택
correlation_vars = ['creativity', 'digital_skill', 'ai_usage']
correlation_matrix = df[correlation_vars].corr()

# 히트맵 시각화
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix of Creativity, Digital Skill, and AI Usage')
plt.show()

from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

X = df[['creativity', 'digital_skill']]
y = df['ai_usage']

# 분석 수행 (Statsmodels 이용 시 상세 레포트 출력 가능)
X_added = sm.add_constant(X)
model = sm.OLS(y, X_added).fit()
print(model.summary())

"""### P-value가 높은 변수 제거 후 회귀 분석 재수행

이전 회귀 분석 결과에서 P-value가 0.05보다 높은 'creativity' 변수를 제거하고, 'digital_skill' 변수만을 사용하여 OLS(Ordinary Least Squares) 회귀 분석을 다시 수행합니다.
"""

X_refined = df[['digital_skill']]
y = df['ai_usage']

# 분석 수행 (Statsmodels 이용 시 상세 레포트 출력 가능)
X_refined_added = sm.add_constant(X_refined)
model_refined = sm.OLS(y, X_refined_added).fit()
print(model_refined.summary())

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

X = df[['digital_skill', 'creativity']]
y = df['is_high_ai']

log_model = LogisticRegression()
log_model.fit(X, y)

print("모델 정확도:", log_model.score(X, y))
print(classification_report(y, log_model.predict(X)))

"""### 'digital_skill'과 'ai_usage' 관계 시각화 (산점도)

'digital_skill'과 'ai_usage' 변수 간의 관계를 산점도(scatter plot)를 통해 시각화하여, 디지털 기술 역량이 AI 활용 능력에 어떤 영향을 미 미치는지 탐색합니다.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 한글 폰트 설정
plt.rcParams['font.family'] = 'NanumBarunGothic'
plt.rcParams['axes.unicode_minus'] = False # 음수 부호 깨짐 방지

plt.figure(figsize=(8, 6))
sns.scatterplot(x='digital_skill', y='ai_usage', data=df, hue='is_high_ai', palette='viridis', s=100, alpha=0.7)
plt.title('Scatter Plot of Digital Skill vs. AI Usage')
plt.xlabel('Digital Skill (점수)')
plt.ylabel('AI Usage (점수)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Is High AI User')
plt.show()

# 폰트 설치
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# 런타임 다시 시작 필요 (주의: Colab에서 폰트 설치 후 런타임 재시작이 필요할 수 있습니다.)